# Generated by Django 5.2.7 on 2025-11-25 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.BigAutoField(db_column='id_anuncio', primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(db_column='id_usuario', max_length=255)),
                ('titulo', models.CharField(blank=True, db_column='titulo', max_length=200, null=True)),
                ('modelo', models.CharField(db_column='modelo', max_length=100)),
                ('anio', models.IntegerField(db_column='anio')),
                ('kilometraje', models.IntegerField(db_column='kilometraje')),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(db_column='descripcion')),
                ('email_contacto', models.CharField(blank=True, db_column='email_contacto', max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, db_column='telefono_contacto', max_length=20, null=True)),
                ('tipo_vehiculo', models.CharField(blank=True, db_column='tipo_vehiculo', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('activo', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'db_table': 'anuncios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id_historial', models.BigAutoField(db_column='id_historial', primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(blank=True, db_column='id_usuario', max_length=255, null=True)),
                ('placa_consultada', models.CharField(blank=True, db_column='placa_consultada', max_length=20, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True, db_column='fecha_consulta')),
                ('resultado_api', models.JSONField(blank=True, db_column='resultado_api', null=True)),
            ],
            options={
                'verbose_name': 'Historial de Búsqueda',
                'verbose_name_plural': 'Historial de Búsquedas',
                'db_table': 'historial_busqueda',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.BigAutoField(db_column='id_notificacion', primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField(blank=True, db_column='id_usuario', null=True)),
                ('id_vendedor', models.CharField(blank=True, db_column='id_vendedor', max_length=255, null=True)),
                ('id_comprador', models.CharField(blank=True, db_column='id_comprador', max_length=255, null=True)),
                ('nombre_comprador', models.CharField(blank=True, db_column='nombre_comprador', max_length=255, null=True)),
                ('email_comprador', models.CharField(blank=True, db_column='email_comprador', max_length=255, null=True)),
                ('id_anuncio', models.BigIntegerField(blank=True, db_column='id_anuncio', null=True)),
                ('titulo', models.CharField(blank=True, db_column='titulo', max_length=200, null=True)),
                ('mensaje', models.TextField(blank=True, db_column='mensaje', null=True)),
                ('leido', models.BooleanField(db_column='leido', default=False)),
                ('leida', models.BooleanField(db_column='leida', default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('metadata', models.JSONField(blank=True, db_column='metadata', null=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.BigAutoField(db_column='id_vehiculo', primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, db_column='placa', max_length=20, null=True, unique=True)),
                ('descripcion_api', models.TextField(blank=True, db_column='descripcion_api', null=True)),
                ('marca', models.CharField(blank=True, db_column='marca', max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, db_column='modelo', max_length=100, null=True)),
                ('anio_registro_api', models.CharField(blank=True, db_column='anio_registro_api', max_length=10, null=True)),
                ('vin', models.CharField(blank=True, db_column='vin', max_length=100, null=True)),
                ('uso', models.CharField(blank=True, db_column='uso', max_length=200, null=True)),
                ('propietario', models.TextField(blank=True, db_column='propietario', null=True)),
                ('delivery_point', models.TextField(blank=True, db_column='delivery_point', null=True)),
                ('fecha_registro_api', models.DateTimeField(blank=True, db_column='fecha_registro_api', null=True)),
                ('image_url_api', models.TextField(blank=True, db_column='image_url_api', null=True)),
                ('datos_api', models.JSONField(blank=True, db_column='datos_api', null=True)),
                ('fecha_actualizacion_api', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion_api')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['-fecha_actualizacion_api'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.BigAutoField(db_column='id_imagen', primary_key=True, serialize=False)),
                ('url_imagen', models.TextField(db_column='url_imagen')),
                ('nombre_archivo', models.CharField(blank=True, db_column='nombre_archivo', max_length=255, null=True)),
                ('tipo_archivo', models.CharField(blank=True, db_column='tipo_archivo', max_length=50, null=True)),
                ('tamano_archivo', models.BigIntegerField(blank=True, db_column='tamaño_archivo', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='fecha_subida')),
                ('orden', models.IntegerField(blank=True, db_column='orden', null=True)),
                ('anuncio', models.ForeignKey(db_column='id_anuncio', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='auth_app.anuncio')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'db_table': 'imagenes',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
    ]
