# Generated by Django 5.2.7 on 2025-11-26 03:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def add_tipo_field_if_not_exists(apps, schema_editor):
    """Agregar campo tipo solo si no existe"""
    # SQLite no requiere esta operación - el campo se agrega automáticamente
    if schema_editor.connection.vendor == 'sqlite':
        return
    
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna ya existe (PostgreSQL)
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='notificaciones' AND column_name='tipo'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE notificaciones 
                ADD COLUMN tipo VARCHAR(50) DEFAULT 'interes'
            """)


def remove_tipo_field_if_exists(apps, schema_editor):
    """Eliminar campo tipo si existe (para rollback)"""
    if schema_editor.connection.vendor == 'sqlite':
        return
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='notificaciones' AND column_name='tipo'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE notificaciones DROP COLUMN IF EXISTS tipo")


def add_tipo_vehiculo_field_if_not_exists(apps, schema_editor):
    """Agregar campo tipo_vehiculo solo si no existe"""
    if schema_editor.connection.vendor == 'sqlite':
        return
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='vehiculos' AND column_name='tipo_vehiculo'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE vehiculos 
                ADD COLUMN tipo_vehiculo VARCHAR(50)
            """)


def remove_tipo_vehiculo_field_if_exists(apps, schema_editor):
    """Eliminar campo tipo_vehiculo si existe (para rollback)"""
    if schema_editor.connection.vendor == 'sqlite':
        return
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='vehiculos' AND column_name='tipo_vehiculo'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE vehiculos DROP COLUMN IF EXISTS tipo_vehiculo")


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        # Primero verificar/crear la columna en la BD si no existe
        migrations.RunPython(
            add_tipo_field_if_not_exists,
            reverse_code=remove_tipo_field_if_exists,
        ),
        # Luego actualizar el estado del modelo (sin tocar la BD)
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No hacer nada en la BD, ya está hecho
            state_operations=[
                migrations.AddField(
                    model_name='notificacion',
                    name='tipo',
                    field=models.CharField(choices=[('interes', 'Interés en Anuncio'), ('mensaje', 'Mensaje'), ('sistema', 'Sistema')], db_column='tipo', default='interes', max_length=50),
                ),
            ]
        ),
        # Verificar/crear tipo_vehiculo en vehiculos
        migrations.RunPython(
            add_tipo_vehiculo_field_if_not_exists,
            reverse_code=remove_tipo_vehiculo_field_if_exists,
        ),
        # Actualizar el estado del modelo para tipo_vehiculo
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No hacer nada en la BD, ya está hecho
            state_operations=[
                migrations.AddField(
                    model_name='vehiculo',
                    name='tipo_vehiculo',
                    field=models.CharField(blank=True, db_column='tipo_vehiculo', max_length=50, null=True),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='anio',
            field=models.IntegerField(db_column='anio', validators=[django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='email_contacto',
            field=models.EmailField(blank=True, db_column='email_contacto', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='id_anuncio',
            field=models.AutoField(db_column='id_anuncio', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='kilometraje',
            field=models.IntegerField(db_column='kilometraje', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='precio',
            field=models.DecimalField(db_column='precio', decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupé'), ('deportivo', 'Deportivo'), ('station-wagon', 'Station Wagon')], db_column='tipo_vehiculo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='id_historial',
            field=models.AutoField(db_column='id_historial', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='id_imagen',
            field=models.AutoField(db_column='id_imagen', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='orden',
            field=models.IntegerField(db_column='orden', default=0),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='email_comprador',
            field=models.EmailField(blank=True, db_column='email_comprador', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id_anuncio',
            field=models.ForeignKey(blank=True, db_column='id_anuncio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.anuncio'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id_notificacion',
            field=models.AutoField(db_column='id_notificacion', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='id_vehiculo',
            field=models.AutoField(db_column='id_vehiculo', primary_key=True, serialize=False),
        ),
    ]
