# Generated by Django 5.2.7 on 2025-12-01 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_notificacion_tipo_vehiculo_tipo_vehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVehiculo',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('codigo', models.CharField(db_column='codigo', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
            ],
            options={
                'verbose_name': 'Categoría de Vehículo',
                'verbose_name_plural': 'Categorías de Vehículos',
                'db_table': 'categorias_vehiculo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, db_column='tipo_vehiculo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios', to='auth_app.categoriavehiculo'),
        ),
    ]
